import { useEffect, useState } from 'react'
import { ArrowRight, BrainCircuit, Check, ClipboardList, Clock, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { EmptyState } from '../components/EmptyState'
import { Loading } from '../components/Loading'
import { api, friendlyError } from '../lib/api'
import type { TestSummary } from '../types'

export function AssessmentsPage(){const [tests,setTests]=useState<TestSummary[]>();const navigate=useNavigate();useEffect(()=>{api.getTests().then(setTests).catch(e=>{toast.error(friendlyError(e));setTests([])})},[]);if(!tests)return <Loading label="Loading assessments…"/>;return <div><div className="max-w-2xl"><p className="eyebrow">Understand your living style</p><h1 className="mt-2 font-[var(--font-display)] text-4xl font-extrabold tracking-tight">Small questions. Better matches.</h1><p className="mt-3 leading-7 text-[#71807b]">Your answers help us find people whose rhythms, communication and idea of home complement yours.</p></div><div className="mt-8 rounded-3xl bg-[#174f3f] p-7 text-white sm:p-9"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex gap-5"><span className="hidden size-14 shrink-0 place-items-center rounded-2xl bg-white/10 sm:grid"><BrainCircuit className="text-[#f3c568]"/></span><div><p className="text-xs font-extrabold uppercase tracking-[.17em] text-[#9ed5c2]">Why it matters</p><h2 className="mt-2 font-[var(--font-display)] text-2xl font-extrabold">Chemistry is more than shared rent.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/65">We turn your answers into compatible patterns — not labels. Your individual responses stay private.</p></div></div><div className="flex gap-5 text-xs font-bold text-white/70"><span className="flex items-center gap-2"><Clock size={16}/> 5–10 min</span><span className="flex items-center gap-2"><Check size={16}/> Private</span></div></div></div><div className="mt-8">{tests.length===0?<EmptyState icon={ClipboardList} title="No active assessments" body="There aren't any assessments published yet. Check back soon or ask an admin to add questions to a test definition."/>:<div className="grid gap-5 md:grid-cols-2">{tests.map((test,i)=><article key={test.id} className="card p-6"><div className="flex items-start justify-between"><span className={`grid size-12 place-items-center rounded-2xl ${i%2?'bg-[#fff0e9] text-[#c86850]':'bg-[#e5f2ed] text-[#27775f]'}`}><Sparkles size={22}/></span><span className="rounded-full bg-[#f1f3ef] px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-[#71807b]">Version {test.version}</span></div><h2 className="mt-6 font-[var(--font-display)] text-xl font-extrabold">{test.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-[#71807b]">{test.description||'A thoughtful assessment designed to improve your compatibility results.'}</p><button onClick={()=>navigate(`/app/assessments/${test.slug}`)} className="mt-5 flex w-full items-center justify-between rounded-xl border border-black/8 px-4 py-3 text-sm font-bold hover:border-[#27775f] hover:bg-[#f4faf7]"><span>Start assessment</span><ArrowRight size={17}/></button></article>)}</div>}</div></div>}
